"""add username field

Revision ID: add_username_field
Revises: 
Create Date: 2024-03-21 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import logging

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision = 'add_username_field'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    logger.info("Starting upgrade: adding username field")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    logger.info("Added username column")
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    logger.info("Created username index")
    # ### end Alembic commands ###


def downgrade() -> None:
    logger.info("Starting downgrade: removing username field")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    logger.info("Dropped username index")
    op.drop_column('users', 'username')
    logger.info("Dropped username column")
    # ### end Alembic commands ### 